# Default values for Dev Environment
global:
  environment: dev
  tenantId: "" # To be filled by pipeline
  registry: ghcr.io # Default to GHCR
  imagePullSecrets:
    - name: regcred

keyVault:
  name: "" # To be filled by pipeline

apps:
  nginx:
    replicaCount: 1
    repository: kube-nginxapp1
    tag: 1.0.0
  java:
    replicaCount: 1
    repository: kube-usermgmt-webapp
    tag: 1.0.0-MySQLDB
    mysql:
      repository: mysql
      tag: 5.6
      password: "dbpassword11"
  dotnet:
    replicaCount: 1
    repository: samples
    tag: aspnetapp

nodeSelectors:
  linux:
    app: system-apps
  windows:
    nodepoolos: windows
