apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This tells Kustomize to add these labels to EVERYTHING in this environment
commonLabels:
  managed-by: gitops
  environment: dev

# We can also add common annotations (like for logging)
commonAnnotations:
  enercity.de/logging-enabled: "true"
  enercity.de/team: "devsecops"

resources:
  - ../../base
